---
# Docker Tasks

- hosts: all
  become: yes
  tasks: 
  - name: install docker dependencies
    apt:
      pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
      state: latest
      update_cache: true

  - name: Add Docker GPG apt Key Debian
    apt_key:
      url: https://download.docker.com/linux/debian/gpg
      state: present
      when: ansible_distribution == 'Debian'
  
  - name: Add Docker GPG apt Key Ubuntu 
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
      when: ansible_distribution == 'Ubuntu'

  - name: Add Docker Repository Debian
    apt_repository:
      repo: deb https://download.docker.com/linux/debian bullseye stable
      state: present
      when: ansible_distribution == 'Debian'
   
  - name: Add Docker Repository Ubuntu
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu jammy stable
      state: present
      when: ansible_distribution == 'Ubuntu'

  - name: Update apt and install docker-ce
    apt:
      name: docker-ce
      state: latest
      update_cache: true
